mysite/urls.py
from django.urls import path
from . import views

app_name = "mysite" 

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('experiences/', views.experience, name='experience'),
    path('project/', views.project, name='project'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name='contact'),
    path('schedule/',views.schedule, name='schedule'),
    path('schedule/make_schedule/',views.create_schedule, name='makeschedule'),
    path('schedule/delete', views.delete)
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mysite.urls')),
]

mysite/models.py
from django.db import models
import datetime
from django.utils import timezone

class Schedule(models.Model):
    kegiatan = models.CharField(max_length=40)
    tempat = models.CharField(max_length=40)
    kategori= models.CharField(null=True, max_length=40)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)
    
    def __str__(self):
        return self.kegiatan

mysite/forms.py
from . import models
from django import forms
import datetime

class mySchedule(forms.ModelForm):
    kegiatan = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "schedule full",
                "required" : True,
                "placeholder": "Nama Kegiatan",
                }))
    tempat = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "schedule full",
                "required" : True,
                "placeholder": "Tempat",
                }))
    kategori = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "schedule full",
                "required" : True,
                "placeholder":"Kategori",
                }))
    tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
                "class" : "datefield jadwalfields",
                "required" : True,
                }), initial=datetime.datetime.now())
    waktu = forms.TimeField(widget=forms.TimeInput(attrs={
                "class" : "datefield jadwalfields",
                "placeholder":"00:00",
                "required" : True,
                }), initial=datetime.datetime.now()) 
    
    class Meta: 
            model = models.Schedule
            fields = ['kegiatan','kategori','tempat','tanggal', 'waktu']

mysite/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import mySchedule
from .models import Schedule
from django.utils import timezone
import datetime

def home(request):
    return render(request,'HOME.html')

def aboutme(request):
    return render(request, 'ABOUTME.html')

def experience(request):
    return render(request, 'EXPERIENCES.html')

def project(request):
    return render(request, 'PROJECT.html')

def gallery(request):
    return render(request, 'GALLERY.html')

def contact(request):
    return render(request, 'CONTACT.html')

def create_schedule(request):
    form = mySchedule()
    if request.method =="POST":
        form = mySchedule(request.POST)
        if form.is_valid():
            form.save()
            return redirect('mysite:schedule')
    return render(request, "MakeSchedule.html",{'form':form})

def schedule(request):
    schedules = Schedule.objects.order_by("tanggal","waktu")
    response = {
        'schedule' : schedules,
        'server_time' : datetime.datetime.now()
    }
    return render(request, "SCHEDULE.html", response)

def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Schedule.objects.get(id=id).delete()
    return redirect('mysite:schedule')
    

mysite/templates/ABOUTME.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}

<p style="color: aliceblue; font-size: 100px; text-align: center"> under costruction</p>

{% endblock %}

mysite/templates/BASE.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <title>SHANS</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <script href="{% static 'js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </head>
<body>
    
    <nav class="navbar navbar-expand-md sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'mysite:home' %}"> SHANS</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#mainNav">
                <span class="navbar-toggler-icon rounded-circle"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainNav" >
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'mysite:aboutme' %}">ABOUT ME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mysite:experience' %}">EXPERIENCES</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mysite:project' %}" >PROJECT</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mysite:gallery' %}" >GALLERY</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mysite:schedule' %}" >SCHEDULE</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mysite:contact' %}" >CONTACT</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block page_content %}
    {% endblock %}

    <div class="footer">
        <a class="footer-logo">made by SHANS</a>
    </div>
</body>
</html>

mysite/templates/CONTACT.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}

<p style="color: aliceblue; font-size: 100px; text-align: center"> under costruction</p>

{% endblock %}

mysite/templates/EXPERIENCES.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}

<p style="color: aliceblue; font-size: 100px; text-align: center"> under costruction</p>

{% endblock %}

mysite/templates/GALLERY.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}

<p style="color: aliceblue; font-size: 100px; text-align: center"> under costruction</p>

{% endblock %}

mysite/templates/HOME.html
{% extends "BASE.html" %}
{% load static %}
{% block page_content %}

<div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="" class="d-block w-100" alt="First Slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Welcome to my website!</h5>
            <p>Let me take you into my own world which is beyond your imagination</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="" class="d-block w-100" alt="Second Slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Welcome to my website!</h5>
            <p>Let me take you into my own world which is beyond your imagination</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="" class="d-block w-100" alt="Third Slide">
          <div class="carousel-caption d-none d-md-block">
            <h5>Third slide label</h5>
            <p>Let me take you into my own world which is beyond your imagination</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

{% endblock %}

mysite/templates/MakeSchedule.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}

<div class="form-container rounded-10">
  <h2>Add Schedule</h2>
  <form method="POST" class="form">
    {% csrf_token %}
    <h5>Nama Kegiatan</h5>
    {{ form.kegiatan }}
    <h5>Tempat Kegiatan</h5>
    {{ form.tempat }}
    <h5> Kategori Kegiatan </h5>
    {{ form.kategori }}
    <h5> Waktu dan Tanggal Kegiatan </h5>
    <p>
      {{ form.waktu }}
      {{ form.tanggal }}
    </p>
    <div class="full">
      <a href="/schedule/"><button type="button" class="button delete">Back</button></a>
      <input type="submit" class="button" value="Submit" />
    </div>
  </form>
</div>

{% endblock %}

mysite/templates/PROJECT.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}

<p style="color: aliceblue; font-size: 100px; text-align: center"> under costruction</p>

{% endblock %}

mysite/templates/SCHEDULE.html
{% extends "BASE.html" %}

{% load static %}
{% block page_content %}
    <div class="sche-container">
        <h1>My Schedule</h1>
        <div class="atas">
            <a href="{% url 'mysite:makeschedule' %}"><button type="button" class="button delete">Create Schedule</button></a>
        </div>
    
    {% for j in schedule %}
        <div class="jadwalsheet">
            <h2><span>{{ j.kategori }}</span> - {{ j.kegiatan }}</h2>
            <div class="keterangan">
                <div>
                    <h4>di {{ j.tempat }}</h4>
                    <p>{{ j.tanggal }} - {{ j.waktu }}</p>
                </div>
                <form action="delete" method="POST" >
                {% csrf_token %}
                    <input type="hidden" value="{{ j.id }}" name="id" />
                    <input class="button delete" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}